language: perl
dist: trusty
install:
  - sudo apt-get install vim
  - cpanm --notest Test::Differences Text::VimColor IO::Pty Test::Deep Parallel::ForkManager JSON Path::Tiny Test::SharedFork Test::LongString
  - git fetch origin p5-corpus-ng:origin/p5-corpus-ng
  - vim --version
script:
  - make test
branches:
  except:
    - p5-corpus
